# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('usn', models.CharField(max_length=10)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
    ]
