# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='usn',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
