# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='contactus',
            name='text',
            field=tinymce.models.HTMLField(default=False),
        ),
        migrations.AddField(
            model_name='contactus',
            name='usn',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
