# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20170330_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='usn',
            field=models.CharField(max_length=10),
        ),
    ]
