# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170330_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='text',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='usn',
        ),
        migrations.AddField(
            model_name='contactus',
            name='mail',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
