# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20170330_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='mail',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='number',
        ),
        migrations.AddField(
            model_name='contactus',
            name='usn',
            field=models.CharField(default='0', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
