# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:43
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20170330_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
