# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
